{
  "hash": "e39185230556bb51a94bcc8d9ecf04ee",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Mini Project 1: Simulation\"\nauthor: \"Alex Tidd\"\n---\n\n\n\nI have followed all rules for collaboration for this project, and I have not used generative AI on this project -Alex Tidd\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(mosaic)\nlibrary(tidyverse)\nlibrary(ggplot2)\n```\n:::\n\n\n\nPlots of the four distributions being tested:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Code from Dr. Higham\n## create population graphs\n\nnorm_df <- tibble(x = seq(3, 17, length.out = 1000),\n                  dens = dnorm(x, mean = 10, sd = 2),\n                  pop = \"normal(10, 4)\")\nunif_df <- tibble(x = seq(7, 13, length.out = 1000),\n                  dens = dunif(x, 7, 13),\n                  pop = \"uniform(7, 13)\")\nexp_df <- tibble(x = seq(0, 10, length.out = 1000),\n                 dens = dexp(x, 0.5),\n                 pop = \"exp(0.5)\")\nbeta_df <- tibble(x = seq(0, 1, length.out = 1000),\n                  dens = dbeta(x, 8, 2),\n                  pop = \"beta(8, 2)\")\n\npop_plot <- bind_rows(norm_df, unif_df, exp_df, beta_df) |>\n  mutate(pop = fct_relevel(pop, c(\"normal(10, 4)\", \"uniform(7, 13)\",\n                                  \"exp(0.5)\", \"beta(8, 2)\")))\n\nggplot(data = pop_plot, aes(x = x, y = dens)) +\n  geom_line() +\n  theme_minimal() +\n  facet_wrap(~ pop, nrow = 1, scales = \"free\") +\n  labs(title = \"Population Distributions for Each Simulation Setting\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\nHistogram for Y_min for N(10, 4)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Code from class\n\nn <- 5            # sample size\nmu <- 10          # population mean\nsigma <- 2        # population standard deviation\n\ngenerate_samp_Nmin <- function(mu, sigma, n) {\n  \n  single_sample_Nmin <- rnorm(n, mu, sigma)\n  sample_Nmin <- min(single_sample_Nmin)\n  \n  return(sample_Nmin)\n}\n\n## test function once:\ngenerate_samp_Nmin(mu = mu, sigma = sigma, n = n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.240507\n```\n\n\n:::\n\n```{.r .cell-code}\nnsim <- 5000      # number of simulations\n\n## code to map through the function. \n## the \\(i) syntax says to just repeat the generate_samp_mean function\n## nsim times\nNmins <- map_dbl(1:nsim, \\(i) generate_samp_Nmin(mu = mu, sigma = sigma, n = n))\n\n## print some of the 5000 means\n## each number represents the sample mean from __one__ sample.\nNmins_df <- tibble(Nmins)\nNmins_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 1\n   Nmins\n   <dbl>\n 1  5.42\n 2  7.76\n 3  6.25\n 4  9.56\n 5  8.05\n 6  8.18\n 7  8.34\n 8  7.55\n 9  7.95\n10  7.06\n# ℹ 4,990 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data = Nmins_df, aes(x = Nmins)) +\n  geom_histogram(colour = \"deeppink4\", fill = \"deeppink1\", bins = 20) +\n  theme_minimal() +\n  labs(x = \"Observed Sample Mins\",\n       title = paste(\"Normal Sampling Distribution of the \\nSample Min when n =\", n))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\nNmins_df |>\n  summarise(mean_samp_dist_Nmin = mean(Nmins),\n            var_samp_dist_Nmin = var(Nmins),\n            sd_samp_dist_Nmin = sd(Nmins))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  mean_samp_dist_Nmin var_samp_dist_Nmin sd_samp_dist_Nmin\n                <dbl>              <dbl>             <dbl>\n1                7.70               1.77              1.33\n```\n\n\n:::\n:::\n\n\n\nHistogram for Y_max for N(10, 4)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Code from class\n\nn <- 5            # sample size\nmu <- 10          # population mean\nsigma <- 2        # population standard deviation\n\ngenerate_samp_Nmax <- function(mu, sigma, n) {\n  \n  single_sample_Nmax <- rnorm(n, mu, sigma)\n  sample_Nmax <- max(single_sample_Nmax)\n  \n  return(sample_Nmax)\n}\n\n## test function once:\ngenerate_samp_Nmax(mu = mu, sigma = sigma, n = n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.08527\n```\n\n\n:::\n\n```{.r .cell-code}\nnsim <- 5000      # number of simulations\n\n## code to map through the function. \n## the \\(i) syntax says to just repeat the generate_samp_mean function\n## nsim times\nNmaxs <- map_dbl(1:nsim, \\(i) generate_samp_Nmax(mu = mu, sigma = sigma, n = n))\n\n## print some of the 5000 means\n## each number represents the sample mean from __one__ sample.\nNmaxs_df <- tibble(Nmaxs)\nNmaxs_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 1\n   Nmaxs\n   <dbl>\n 1  12.5\n 2  12.3\n 3  12.3\n 4  11.0\n 5  11.2\n 6  12.8\n 7  10.9\n 8  10.4\n 9  12.7\n10  11.4\n# ℹ 4,990 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data = Nmaxs_df, aes(x = Nmaxs)) +\n  geom_histogram(colour = \"deeppink4\", fill = \"deeppink1\", bins = 20) +\n  theme_minimal() +\n  labs(x = \"Observed Sample Maxes\",\n       title = paste(\"Normal Sampling Distribution of the \\nSample Max when n =\", n))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\nNmaxs_df |>\n  summarise(mean_samp_dist_Nmax = mean(Nmaxs),\n            var_samp_dist_Nmax = var(Nmaxs),\n            sd_samp_dist_Nmax = sd(Nmaxs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  mean_samp_dist_Nmax var_samp_dist_Nmax sd_samp_dist_Nmax\n                <dbl>              <dbl>             <dbl>\n1                12.4               1.79              1.34\n```\n\n\n:::\n:::\n\n\n\nHistogram for Y_min for Unif(7, 13)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Code from class\n\ntheta1 <- 7\ntheta2 <- 13\nn <- 5\n\ngenerate_samp_Umin <- function(n, theta1, theta2) {\n  \n  single_sample_Umin <- runif(n, theta1, theta2)\n  sample_Umin <- min(single_sample_Umin)\n  \n  return(sample_Umin)\n}\n\n## test function once:\ngenerate_samp_Umin(n = n, theta1 = theta1, theta2 = theta2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.179087\n```\n\n\n:::\n\n```{.r .cell-code}\nnsim <- 5000      # number of simulations\n\n## code to map through the function. \n## the \\(i) syntax says to just repeat the generate_samp_mean function\n## nsim times\nUmins <- map_dbl(1:nsim, \\(i) generate_samp_Umin(n = n, theta1 = theta1, theta2 = theta2))\n\n## print some of the 5000 means\n## each number represents the sample mean from __one__ sample.\nUmins_df <- tibble(Umins)\nUmins_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 1\n   Umins\n   <dbl>\n 1  8.82\n 2  7.44\n 3  7.34\n 4  7.25\n 5  7.00\n 6  8.38\n 7  8.04\n 8  9.00\n 9  7.20\n10  7.10\n# ℹ 4,990 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data = Umins_df, aes(x = Umins)) +\n  geom_histogram(colour = \"deeppink4\", fill = \"deeppink1\", bins = 20) +\n  theme_minimal() +\n  labs(x = \"Observed Sample Mins\",\n       title = paste(\"Uniform Sampling Distribution of the \\nSample Min when n =\", n))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\nNmins_df |>\n  summarise(mean_samp_dist_Umin = mean(Umins),\n            var_samp_dist_Umin = var(Umins),\n            sd_samp_dist_Umin = sd(Umins))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  mean_samp_dist_Umin var_samp_dist_Umin sd_samp_dist_Umin\n                <dbl>              <dbl>             <dbl>\n1                8.01              0.758             0.870\n```\n\n\n:::\n:::\n\n\n\nHistogram for Y_max for Unif(7, 13)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Code from class\n\ntheta1 <- 7\ntheta2 <- 13\nn <- 5\n\ngenerate_samp_Umax <- function(n, theta1, theta2) {\n  \n  single_sample_Umax <- runif(n, theta1, theta2)\n  sample_Umax <- max(single_sample_Umax)\n  \n  return(sample_Umax)\n}\n\n## test function once:\ngenerate_samp_Umax(n = n, theta1 = theta1, theta2 = theta2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 12.34195\n```\n\n\n:::\n\n```{.r .cell-code}\nnsim <- 5000      # number of simulations\n\n## code to map through the function. \n## the \\(i) syntax says to just repeat the generate_samp_mean function\n## nsim times\nUmaxs <- map_dbl(1:nsim, \\(i) generate_samp_Umax(n = n, theta1 = theta1, theta2 = theta2))\n\n## print some of the 5000 means\n## each number represents the sample mean from __one__ sample.\nUmaxs_df <- tibble(Umaxs)\nUmaxs_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 1\n   Umaxs\n   <dbl>\n 1  10.0\n 2  11.7\n 3  12.8\n 4  11.1\n 5  12.6\n 6  12.1\n 7  12.2\n 8  12.0\n 9  12.8\n10  12.5\n# ℹ 4,990 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data = Umaxs_df, aes(x = Umaxs)) +\n  geom_histogram(colour = \"deeppink4\", fill = \"deeppink1\", bins = 20) +\n  theme_minimal() +\n  labs(x = \"Observed Sample Maxes\",\n       title = paste(\"Uniform Sampling Distribution of the \\nSample Max when n =\", n))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\nNmaxs_df |>\n  summarise(mean_samp_dist_Umax = mean(Umaxs),\n            var_samp_dist_Umax = var(Umaxs),\n            sd_samp_dist_Umax = sd(Umaxs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  mean_samp_dist_Umax var_samp_dist_Umax sd_samp_dist_Umax\n                <dbl>              <dbl>             <dbl>\n1                12.0              0.698             0.835\n```\n\n\n:::\n:::\n\n\n\nHistogram for Y_min for Exp(0.5)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Code from class\n\nlambdaE <- 0.5\nn <- 5\n\ngenerate_samp_Emin <- function(n, lambdaE) {\n  \n  single_sample_Emin <- rexp(n, lambdaE)\n  sample_Emin <- min(single_sample_Emin)\n  \n  return(sample_Emin)\n}\n\n## test function once:\ngenerate_samp_Emin(n = n, lambdaE = lambdaE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2913763\n```\n\n\n:::\n\n```{.r .cell-code}\nnsim <- 5000      # number of simulations\n\n## code to map through the function. \n## the \\(i) syntax says to just repeat the generate_samp_mean function\n## nsim times\nEmins <- map_dbl(1:nsim, \\(i) generate_samp_Emin(n = n, lambdaE = lambdaE))\n\n## print some of the 5000 means\n## each number represents the sample mean from __one__ sample.\nEmins_df <- tibble(Emins)\nEmins_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 1\n    Emins\n    <dbl>\n 1 0.862 \n 2 0.712 \n 3 0.0729\n 4 0.340 \n 5 0.178 \n 6 0.417 \n 7 0.454 \n 8 0.896 \n 9 0.385 \n10 0.461 \n# ℹ 4,990 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data = Emins_df, aes(x = Emins)) +\n  geom_histogram(colour = \"deeppink4\", fill = \"deeppink1\", bins = 20) +\n  theme_minimal() +\n  labs(x = \"Observed Sample Mins\",\n       title = paste(\"Exponential Sampling Distribution of the \\nSample Min when n =\", n))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\nEmins_df |>\n  summarise(mean_samp_dist_Emin = mean(Emins),\n            var_samp_dist_Emin = var(Emins),\n            sd_samp_dist_Emin = sd(Emins))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  mean_samp_dist_Emin var_samp_dist_Emin sd_samp_dist_Emin\n                <dbl>              <dbl>             <dbl>\n1               0.400              0.166             0.408\n```\n\n\n:::\n:::\n\n\n\nHistogram for Y_max for Exp(0.5)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Code from class\n\nlambdaE <- 0.5\nn <- 5\n\ngenerate_samp_Emax <- function(n, lambdaE) {\n  \n  single_sample_Emax <- rexp(n, lambdaE)\n  sample_Emax <- max(single_sample_Emax)\n  \n  return(sample_Emax)\n}\n\n## test function once:\ngenerate_samp_Emax(n = n, lambdaE = lambdaE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.476872\n```\n\n\n:::\n\n```{.r .cell-code}\nnsim <- 5000      # number of simulations\n\n## code to map through the function. \n## the \\(i) syntax says to just repeat the generate_samp_mean function\n## nsim times\nEmaxs <- map_dbl(1:nsim, \\(i) generate_samp_Emax(n = n, lambdaE = lambdaE))\n\n## print some of the 5000 means\n## each number represents the sample mean from __one__ sample.\nEmaxs_df <- tibble(Emaxs)\nEmaxs_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 1\n   Emaxs\n   <dbl>\n 1  7.28\n 2  5.46\n 3  5.67\n 4  2.75\n 5  3.39\n 6  3.97\n 7  2.45\n 8  4.04\n 9  1.99\n10  3.55\n# ℹ 4,990 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data = Emaxs_df, aes(x = Emaxs)) +\n  geom_histogram(colour = \"deeppink4\", fill = \"deeppink1\", bins = 20) +\n  theme_minimal() +\n  labs(x = \"Observed Sample Maxes\",\n       title = paste(\"Exponential Sampling Distribution of the \\nSample Max when n =\", n))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\nEmaxs_df |>\n  summarise(mean_samp_dist_Emax = mean(Emaxs),\n            var_samp_dist_Emax = var(Emaxs),\n            sd_samp_dist_Emax = sd(Emaxs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  mean_samp_dist_Emax var_samp_dist_Emax sd_samp_dist_Emax\n                <dbl>              <dbl>             <dbl>\n1                4.61               6.23              2.50\n```\n\n\n:::\n:::\n\n\n\nHistogram for Y_min for Beta(8, 2)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Code from class\n\nalpha <- 8\nbeta <- 2\nn <- 5\n\ngenerate_samp_Bmin <- function(n, alpha, beta) {\n  \n  single_sample_Bmin <- rbeta(n, alpha, beta)\n  sample_Bmin <- min(single_sample_Bmin)\n  \n  return(sample_Bmin)\n}\n\n## test function once:\ngenerate_samp_Bmin(n = n, alpha = alpha, beta = beta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8144297\n```\n\n\n:::\n\n```{.r .cell-code}\nnsim <- 5000      # number of simulations\n\n## code to map through the function. \n## the \\(i) syntax says to just repeat the generate_samp_mean function\n## nsim times\nBmins <- map_dbl(1:nsim, \\(i) generate_samp_Bmin(n = n, alpha = alpha, beta = beta))\n\n## print some of the 5000 means\n## each number represents the sample mean from __one__ sample.\nBmins_df <- tibble(Bmins)\nBmins_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 1\n   Bmins\n   <dbl>\n 1 0.667\n 2 0.770\n 3 0.658\n 4 0.712\n 5 0.757\n 6 0.568\n 7 0.535\n 8 0.373\n 9 0.662\n10 0.413\n# ℹ 4,990 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data = Bmins_df, aes(x = Bmins)) +\n  geom_histogram(colour = \"deeppink4\", fill = \"deeppink1\", bins = 20) +\n  theme_minimal() +\n  labs(x = \"Observed Sample Mins\",\n       title = paste(\"Beta Sampling Distribution of the \\nSample Min when n =\", n))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\nBmins_df |>\n  summarise(mean_samp_dist_Bmin = mean(Bmins),\n            var_samp_dist_Bmin = var(Bmins),\n            sd_samp_dist_Bmin = sd(Bmins))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  mean_samp_dist_Bmin var_samp_dist_Bmin sd_samp_dist_Bmin\n                <dbl>              <dbl>             <dbl>\n1               0.647             0.0110             0.105\n```\n\n\n:::\n:::\n\n\n\nHistogram for Y_max for Beta(8, 2)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Code from class\n\nalpha <- 8\nbeta <- 2\nn <- 5\n\ngenerate_samp_Bmax <- function(n, alpha, beta) {\n  \n  single_sample_Bmax <- rbeta(n, alpha, beta)\n  sample_Bmax <- max(single_sample_Bmax)\n  \n  return(sample_Bmax)\n}\n\n## test function once:\ngenerate_samp_Bmax(n = n, alpha = alpha, beta = beta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9575138\n```\n\n\n:::\n\n```{.r .cell-code}\nnsim <- 5000      # number of simulations\n\n## code to map through the function. \n## the \\(i) syntax says to just repeat the generate_samp_mean function\n## nsim times\nBmaxs <- map_dbl(1:nsim, \\(i) generate_samp_Bmax(n = n, alpha = alpha, beta = beta))\n\n## print some of the 5000 means\n## each number represents the sample mean from __one__ sample.\nBmaxs_df <- tibble(Bmaxs)\nBmaxs_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5,000 × 1\n   Bmaxs\n   <dbl>\n 1 0.937\n 2 0.953\n 3 0.940\n 4 0.904\n 5 0.961\n 6 0.916\n 7 0.964\n 8 0.954\n 9 0.963\n10 0.922\n# ℹ 4,990 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(data = Bmaxs_df, aes(x = Bmaxs)) +\n  geom_histogram(colour = \"deeppink4\", fill = \"deeppink1\", bins = 20) +\n  theme_minimal() +\n  labs(x = \"Observed Sample Maxes\",\n       title = paste(\"Beta Sampling Distribution of the \\nSample Max when n =\", n))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\nBmaxs_df |>\n  summarise(mean_samp_dist_Bmax = mean(Bmaxs),\n            var_samp_dist_Bmax = var(Bmaxs),\n            sd_samp_dist_Bmax = sd(Bmaxs))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  mean_samp_dist_Bmax var_samp_dist_Bmax sd_samp_dist_Bmax\n                <dbl>              <dbl>             <dbl>\n1               0.922            0.00205            0.0453\n```\n\n\n:::\n:::\n\n\n\n|   | $\\text{N}(\\mu = 10, \\sigma^2 = 4)$ | $\\text{Unif}(\\theta_1 = 7, \\theta_2 = 13)$ | $\\text{Exp}(\\lambda = 0.5)$ | $\\text{Beta}(\\alpha = 8, \\beta = 2)$ |\n|:-------------:|:-------------:|:-------------:|:-------------:|:-------------:|\n| $\\text{E}(Y_{min})$ | 7.94 | 8.00 | 0.391 | 0.650 |\n| $\\text{E}(Y_{max})$ | 12.0 | 12.0 | 4.59 | 0.922 |\n|  |  |  |  |  |\n| $\\text{SE}(Y_{min})$ | 1.41 | 0.852 | 0.386 | 0.104 |\n| $\\text{SE}(Y_{max})$ | 1.93 | 0.872 | 2.40 | 0.0461 |\n\n: Table of Results {.striped .hover}\n\nAnalysis of SE(Y_min) and SE(Y_max)\n\nFor the normal distribution the SE(Y_min) was 1.41 and the SE(Y_max) was 1.93. What is notable about this is that the two SE are relatively the same. Which makes sense because a normal distribution is generally symmetrical so our sampling distributions of Y_min and Y_max should have a relatively similar SE.\n\nFor the uniform distribution we see a similar result to the normal distribution. SE(Y_min) was 0.852 and SE(Y_max) was 0.857. This is expected since a uniform distribution is perfectly symmetrical and \"uniform\" throughout the entire distribution.\n\nFor the exponential distribution, we get our first big change from the normal and uniform results. For the exponential distribution we get an SE(Y_min) of 0.386 and an SE(Y_max) of 2.40. This makes sense since in an exponential distribution we get an extremely high amount of density around the lower end meaning our minimum doesn't vary much. But, as you you continue towards infinity, we get little density and much more variance between maximums.\n\nWith the beta distribution we see almost a mix of results from the normal and exponential. We see anb SE(Y_min) of 0.104 and an SE(Y_max) of 0.0461. So the the SE(Y_min) and SE(Y_max) do appear to be relatively different, but not as much as the exponential. Which makes sense if we look at the beta distribution, we see a normal looking distribution with a left skew, which indicates more variance of the Y_min.\n\nA general rule for SE(Y_min) and SE(Y_max) could be: If the distribution is symmetrical, the SE(Y_min) and SE(Y_max) should be relatively identical wheras a skewed distribution should have very different SE(Y_min) and SE(Y_max).\n\nQuestion 2: PDF of Y_min and Y_max of Exponential distribution:\n\nPDF of Exp(0.5) = 0.5 \\* exp(-0.5 \\* x) from 0 to infinity CDF of Exp(0.5) = 1 - exp(-0.5 \\* x) from 0 to infinity\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn = 5\nx = seq(0, 5, length.out = 1000)\n\n## Y_min and Y_max densities using PDF and CDF above\ndensity_min = n * ((-1 * exp(-0.5 * x))^4) * (0.5 * exp(-0.5 * x))\ndensity_max = n * ((1 - exp(-0.5 * x))^4) * (0.5 * exp(-0.5 * x))\n\n## Plotting the density of Y_min\nEXPmin_df = tibble(x, density_min)\nggplot(data = EXPmin_df, aes(x = x, y = density_min)) +\n  geom_line() +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\n## Plotting the density of Y_max\nEXPmax_df = tibble(x, density_max)\nggplot(data = EXPmax_df, aes(x = x, y = density_max)) +\n  geom_line() +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n\n```{.r .cell-code}\n## Integrating to find E(Y_min) and E(Y_max)\n## Starting by making functions of the integrand\nintY_min = function(y) {\n  y * 5 * ((-1 * exp(-0.5 * y))^4) * (0.5 * exp(-0.5 * y))\n}\n\nintY_max = function(y) {\n  y * 5 * ((1 - exp(-0.5 * y))^4) * (0.5 * exp(-0.5 * y))\n}\n\n## finding E(Y_min) and E(Y_max) via integrate() function\n\n(EY_min = integrate(intY_min, 0, Inf))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n0.4 with absolute error < 5.3e-05\n```\n\n\n:::\n\n```{.r .cell-code}\n(EY_max = integrate(intY_max, 0, Inf))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n4.566667 with absolute error < 3.9e-05\n```\n\n\n:::\n:::\n\n\n\nThe theoretical E(Y_min) is 0.4 and the theoretical E(Y_max) is 4.567. Our simulated model had E(Y_min) at 0.391 and E(Y_max) at 4.59. We see that the teoretical answers and the simulated answers for E(Y_min) and E(Y_max) are extremely close!\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}