{
  "hash": "dea855a0ba439c105b11707f2f0aa13c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Mini Project 3: Simulation to Investigate Confidence Intervals\"\nauthor: \"Alex Tidd\"\n---\n\n\n\n“I have followed all rules for collaboration for this project, and I have not used generative AI on this project.” - Alex Tidd\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(mosaic)\nlibrary(ggplot2)\nlibrary(resample)\n```\n:::\n\n\n\nFor the three population sizes we will be using n1 = 5, n2 = 50, and n3 = 5000. For the two population proportions, we will use p1 = 0.45 and p2 = 0.9.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## creating a function using Dr. Higham's code from lab 3.2\n\ngenerate_samp_prop <- function(n, p) {\n  x <- rbinom(1, n, p) # randomly generate number of successes for the sample\n  \n  ## number of successes divided by sample size\n  phat <- x / n\n  lb <- phat - qt(0.95, n-1) * sqrt(phat * (1 - phat) / n)\n  ub <- phat + qt(0.95, n-1) * sqrt(phat * (1 - phat) / n)\n  \n  prop_df <- tibble(phat, lb, ub)\n  \n  return(prop_df)\n}\n```\n:::\n\n\n\nCreating 5000 sample proportions and 5000 associated CIs for n = 5000 and p = 0.45 and finding coverage rate and average width.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Code from Dr. Higham's Lab 3.1\ngenerate_samp_prop(5000, 0.45)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   phat    lb    ub\n  <dbl> <dbl> <dbl>\n1 0.454 0.443 0.466\n```\n\n\n:::\n\n```{.r .cell-code}\nn_sim <- 5000\n\nprop_ci_df_large_near <- map(1:n_sim, \n    \\(i) generate_samp_prop(5000, 0.45)) |>\n  bind_rows()\n\n## finding coverage rate and avg width using code provided in Dr. Higham's Lab 3.2\nprop_ci_df_large_near <- prop_ci_df_large_near |>\n  mutate(ci_width = ub - lb,\n         ci_cover_ind = if_else(0.45 > lb & 0.45 < ub,\n                                true = 1,\n                                false = 0)) |>\n  summarise(avg_width = mean(ci_width),\n            coverage_rate = mean(ci_cover_ind))\n\nprop_ci_df_large_near\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_width coverage_rate\n      <dbl>         <dbl>\n1    0.0231         0.894\n```\n\n\n:::\n:::\n\n\n\nWe see that in this case the average width is 0.0231 and the coverage rate is 0.901.\n\nLets move on to n = 5000 but now p = 0.9\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngenerate_samp_prop(5000, 0.9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   phat    lb    ub\n  <dbl> <dbl> <dbl>\n1 0.899 0.892 0.906\n```\n\n\n:::\n\n```{.r .cell-code}\nn_sim <- 5000\n\nprop_ci_df_large_far <- map(1:n_sim, \n    \\(i) generate_samp_prop(5000, 0.9)) |>\n  bind_rows()\n\n## finding coverage rate and avg width using code provided in Dr. Higham's Lab 3.2\nprop_ci_df_large_far <- prop_ci_df_large_far |>\n  mutate(ci_width = ub - lb,\n         ci_cover_ind = if_else(0.9 > lb & 0.9 < ub,\n                                true = 1,\n                                false = 0)) |>\n  summarise(avg_width = mean(ci_width),\n            coverage_rate = mean(ci_cover_ind))\n\nprop_ci_df_large_far\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_width coverage_rate\n      <dbl>         <dbl>\n1    0.0140         0.899\n```\n\n\n:::\n:::\n\n\n\nIn this case we see that avg width is 0.0140 and the coverage rate is 0.896.\n\nNext up is n = 50 and p = 0.45\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngenerate_samp_prop(50, 0.45)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   phat    lb    ub\n  <dbl> <dbl> <dbl>\n1  0.38 0.265 0.495\n```\n\n\n:::\n\n```{.r .cell-code}\nn_sim <- 5000\n\nprop_ci_df_mid_near <- map(1:n_sim, \n    \\(i) generate_samp_prop(50, 0.45)) |>\n  bind_rows()\n\n## finding coverage rate and avg width using code provided in Dr. Higham's Lab 3.2\nprop_ci_df_mid_near <- prop_ci_df_mid_near |>\n  mutate(ci_width = ub - lb,\n         ci_cover_ind = if_else(0.45 > lb & 0.45 < ub,\n                                true = 1,\n                                false = 0)) |>\n  summarise(avg_width = mean(ci_width),\n            coverage_rate = mean(ci_cover_ind))\n\nprop_ci_df_mid_near\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_width coverage_rate\n      <dbl>         <dbl>\n1     0.234         0.915\n```\n\n\n:::\n:::\n\n\n\nIn this case we see that the average width is 0.233 and the coverage rate is 0.914\n\nNext up let's take a look at a medium size n again but this time with a p far from 0.5\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngenerate_samp_prop(50, 0.9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   phat    lb    ub\n  <dbl> <dbl> <dbl>\n1  0.86 0.778 0.942\n```\n\n\n:::\n\n```{.r .cell-code}\nn_sim <- 5000\n\nprop_ci_df_mid_far <- map(1:n_sim, \n    \\(i) generate_samp_prop(50, 0.9)) |>\n  bind_rows()\n\n## finding coverage rate and avg width using code provided in Dr. Higham's Lab 3.2\nprop_ci_df_mid_far <- prop_ci_df_mid_far |>\n  mutate(ci_width = ub - lb,\n         ci_cover_ind = if_else(0.9 > lb & 0.9 < ub,\n                                true = 1,\n                                false = 0)) |>\n  summarise(avg_width = mean(ci_width),\n            coverage_rate = mean(ci_cover_ind))\n\nprop_ci_df_mid_far\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_width coverage_rate\n      <dbl>         <dbl>\n1     0.138         0.867\n```\n\n\n:::\n:::\n\n\n\nFor this setting we see and average width of 0.138 and a coverage rate of 0.866\n\nFor the last two rounds we are using a very small n of 5. This should be \"interesting\" to say the least.\n\nn = 5 and p = 0.45\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngenerate_samp_prop(5, 0.45)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   phat      lb    ub\n  <dbl>   <dbl> <dbl>\n1   0.4 -0.0671 0.867\n```\n\n\n:::\n\n```{.r .cell-code}\nn_sim <- 5000\n\nprop_ci_df_small_near <- map(1:n_sim, \n    \\(i) generate_samp_prop(5, 0.45)) |>\n  bind_rows()\n\n## finding coverage rate and avg width using code provided in Dr. Higham's Lab 3.2\nprop_ci_df_small_near <- prop_ci_df_small_near |>\n  mutate(ci_width = ub - lb,\n         ci_cover_ind = if_else(0.45 > lb & 0.45 < ub,\n                                true = 1,\n                                false = 0)) |>\n  summarise(avg_width = mean(ci_width),\n            coverage_rate = mean(ci_cover_ind))\n\nprop_ci_df_small_near\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_width coverage_rate\n      <dbl>         <dbl>\n1     0.812         0.927\n```\n\n\n:::\n:::\n\n\n\nwith small n, we are seeing an average width of 0.819 and a coverage rate of 0.935.\n\nFinally, we will use n = 5 and p = 0.9\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngenerate_samp_prop(5, 0.9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n   phat    lb    ub\n  <dbl> <dbl> <dbl>\n1     1     1     1\n```\n\n\n:::\n\n```{.r .cell-code}\nn_sim <- 5000\n\nprop_ci_df_small_far <- map(1:n_sim, \n    \\(i) generate_samp_prop(5, 0.9)) |>\n  bind_rows()\n\n## finding coverage rate and avg width using code provided in Dr. Higham's Lab 3.2\nprop_ci_df_small_far <- prop_ci_df_small_far |>\n  mutate(ci_width = ub - lb,\n         ci_cover_ind = if_else(0.9 > lb & 0.9 < ub,\n                                true = 1,\n                                false = 0)) |>\n  summarise(avg_width = mean(ci_width),\n            coverage_rate = mean(ci_cover_ind))\n\nprop_ci_df_small_far\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  avg_width coverage_rate\n      <dbl>         <dbl>\n1     0.334         0.412\n```\n\n\n:::\n:::\n\n\n\nfor this we see an average width of 0.324 and a coverage rate of 0.392. Very peculiar if I do say so myself.\n\nNow lets put these splendid results in a table:\n\n|    $p$     |               | $n = 5$ | $n = 50$ | $n = 5000$ |\n|:----------:|:-------------:|:-------:|:--------:|:----------:|\n| $p = 0.45$ | Coverage Rate |  0.935  |  0.914   |   0.901    |\n| $p = 0.9$  | Coverage Rate |  0.392  |  0.866   |   0.896    |\n|            |               |         |          |            |\n| $p = 0.45$ | Average Width |  0.819  |  0.233   |   0.0231   |\n| $p = 0.9$  | Average Width |  0.324  |  0.138   |   0.0140   |\n\n: Table of Results {.striped .hover}\n\nNow lets take a look into how the large sample assumption holds for each setting. To start we will determine in n is large enough for the \"Wald\" interval using n \\* p_hat \\> 10 and n \\* (1 - p_hat) \\> 10.\n\n| $\\hat{p}$ | $n$  | $n\\hat{p}$ | $n (1 - \\hat{p})$ | $Both > 10$ |\n|:---------:|:----:|:----------:|:-----------------:|:-----------:|\n|  $0.45$   | 5000 |    2250    |       2750        |    True     |\n|   $0.9$   | 5000 |    4500    |        500        |    True     |\n|  $0.45$   |  50  |    22.5    |       27.5        |    True     |\n|   $0.9$   |  50  |     45     |         5         |    False    |\n|  $0.45$   |  5   |    2.25    |       2.75        |    False    |\n|   $0.9$   |  5   |    4.5     |        0.5        |    False    |\n\n: Table of Results {.striped .hover}\n\nSo, here we see that in three cases, our assumption of large sample does not hold, which matches our first table of results.\n\nDiscussion:\n\nFor this simulation of confidence intervals, sample size, n, was varied between 5, 50, and 5000. Furthermore our p_hat, was varied between 0.45 and 0.9. In order to see how the large sample assumption holds for assymptotic confidence intervals of proportion, average width of confidence interval and coverage rate of confidence interval was found.\n\nIn order to test this, expected results are as follws: As p_hat approaches 0.5, we should see the largest average width compared with average witdth of same sample size, and as n is increased, we should see a decrease in average width, when p_hat is held constant. This is because our width parameter is defined as: $$\\sqrt{\\frac{\\hat{p}(1 - \\hat{p})}{n}}$$ Furthermore, we expect coverage rate to stay the same throughout this simulation as that is solely depended on our confidence level. The only time this should change is when confidence level is adjusted, which in this experiment, it remains at 90%. So in this case coverage rate should be around 0.9.\n\nThe results in this experiment followed theory to a tee. When using the \"Wald\" interval for confidence interval of a proportion, you must make sure the np \\> 10 and n(1 - p) \\> 10 for our assumptions to hold. In this case, 3 of the 6 intervals tested upheld this stipulation, n = 5000 and p = 0.45, n = 5000 and p = 0.9, and n = 50 and p = 0.45.\n\nIn the case of n = 5000, we see that when p = 0.45, the average width was roughly 0.0231 compared to when p = 0.9 at average width roughly 0.0140. This follows what we expect as when n is held constant, p further from 0.5 will have a smaller average width. Furthermore, the average widths of n = 5000 we're also the smallest when p is held constant, like we expect. And for both n = 5000, coverage rate is approximately 0.9.\n\nIn the case of n = 50, our assumption only holds when p = 0.45. We see a smaller average width when p = 0.9, as expected. However, coverage rate is only approximately 0.9 when p = 0.45. This is as expected since when n = 50 and p = 0.9, the stipulation of n(1 - p) \\> 10 is not upheld. So we see that when n is mid-sized, the large sample assumption is only upheald when p is close to 0.5.\n\nLastly, small n. When n = 5, we see that neither np \\> 10 nor n(1 - p) \\> 10 is upheld. The results of this simulation reflect this. The average widths followed our expected pattern, however the widths 0.819 for p = 0.45 and 0.324 for p = 0.9, which are very large widths and don't really tell you anything since proportions can only be between 0 and 1. So a width of 0.8 is basically like saying \"we're 90% confident it could be anywhere\". And lastly, the coverage rates were approximately 0.93 for p = 0.45 and 0.39 for n = 0.9. Which essientiall means for p = 0.9 we wanted a 90% confidence interval and only came away with a 40% confidence interval. And comparing that to an average with of 0.324 being only a 40% confidence level, a 90% confidence interval would have very large bounds, running into the same issue as n = 5 and p = 0.45, where the confidence interval really only tells you that it is somewhere.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}