---
title: "Mini Project 2: A Meaningful Story"
author: "Alex Tidd"
---

Up in the Northeast corner of New York lies a place no more polar than St. Lawrence County. From the bright, warm, and breezy springtime to the sweltering, Sahara-like summers, and finally to the frigid, dank, and sterile winters, there is no crazier county in the state.

Nestled in this large county, the largest in the state might I add, lies four accredited universities, St. Lawrence University, a small liberal arts college, that for no reason at all has an incredibly strong math department. Clarkson University, an engineering school that prides itself on claiming that their school “actually gets people hired” (when challenged with the argument that SLU has the 2nd best alumni network in the country amongst private schools, they revert to saying that at least their getting a BS. When challenged with, “So am I”, there is no rebuttal). Then there’s SUNY Potsdam, a school that is literally only being kept afloat by its music program. And finally, SUNY Canton, consistently described as “a university”.

What keeps these four schools together as one “big family” is the fact that each school is well equipped and extremely familiar with the snow. There is simply no such thing as “schoolwide class closure due to inclement weather”. Some (I) have experienced walking to CHEM 222 with frozen tears in -30 degree weather (243 K). Those tears quickly unfreeze and start pouring when the students are made aware that schools like the University of Tennessee closing due to an inch of snow. This was soon about to change.

One day a St. Lawrence student, Alex, was going to Waltham, MA to visit his younger brother, Brendan, at his place of higher education, Bentley University, where he studies accounting. Before heading down to the Boston area, Alex’s CS 140 professor, Dr. Choong-Soo Lee, made him aware that he should leave on Wednesday, the day before a massive snowstorm. Alex, an experienced snow driver, hailing from Rochester, NY, disregarded this advice since he knows that when it comes to weather apps, he feels like predicted snowfall is consistently biased-high, and feels like he’ll be able to manage in his 2018 Jeep Grand Cherokee equipped with BFGoodrich All-Terrain T/A KO3 tires. And managed he did. He also noted that in fact the actual snowfall was less than estimated, biased-high, some statisticians might say.

Upon arriving at Bentley and spending time with brother, Alex expressed his desire to return to St. Lawrence on Sunday. “OH NO!” expressed his brother Brendan. Alex was bewildered with this statement, did his brother want him to spend more quality time with him, yes, as Alex would too, but his voice seemed too concerned for that to be the case. Brendan continued, “There’s going to be a massive snowstorm Sunday in the Northeast! Bentley has already cancelled class Monday”.

Alex, in all of his infinite wisdom and confidence arrogantly stated: “Pfft in all my four years at St. Lawrence, not once have I had a snow day! It simply doesn’t exist in North Country School Vocab. Besides, the estimators used by the weather app are all biased high”. Brendan challenged Alex on this statement and an intense statistics battle broke out (talk about a thesis defense). Brendan started the argument: Alex lets first consider the northeast, snowfall is most likely going to normally distributed here, let snowfall be a random variable, this means that the weather apps expected snowfall of 3ft is the mean! You’re gonna get hit with three ft of snow overnight! Alex rebuts: Brendan, that is the entire Northeast. Let’s just take a sample of that and make a sampling distribution of the mean snowfalls of schools in my area: SUNY Potsdam, SUNY Canton, St. Lawrence, and Clarkson, and for good measure, we’ll throw in Paul Smith’s University as well, since this is what I’m going to drive through (please note that in a real sampling distribution these places would be chosen at random). Brendan, this sample mean is legitimately 1 foot. That is light work. Furthermore, the weather app finds its snowfall estimator using the Maximum Likelihood Estimator. A method of finding an estimator based off maximizing the likelihood of an estimator using calculus but neglected to find the methods of moments estimator even though the MLE is biased (at least in my experience with weather prediction)!!! “SO BOOM I WIN” exclaimed Alex, citing his educational superiority over a measly accounting major at a business school. But Alex was about to find out just how wrong he was.

After waking up, seeing that the four North Country Universities had cancelled classes (for like the first time ever), and deciding to not check his phone to see a St. Lawrence County travel ban, Alex found himself ripping up I-90W to I-87N. Alex entered the stretch of I-87N that enters the Adirondack State Park. He found himself on an unplowed stretch of interstate going 40 MPH behind a semi. “Maybe Brendan was right” he thought. Then, stupidly and arrogantly, he got off at exit 26, Pottersville-Minerva, NY. The situation quickly got serious. Alex was driving through the Adirondacks in a blizzard over unplowed roads with like 3ft of snow on the ground. Then Alex realized “OH NO I FORGOT TO TAKE VARIENCE INTO CONSIDERATION!”. Alex quickly realized to things, 1) His “Sampling distribution” was not done properly (it was not a bunch of random samples, instead he handpicked 5 random cases and only took one simulation of it), and 2) He did not use the var() function in R. Alex realized his small sample size had a HUGE variance and that 3ft of snow, even though not the expected value, was within the range of the variance of the distribution. Alex thought to himself “Dr. Higham is going to kill me” and “Brendan, my kid brother, was right and I should’ve listened to him”.

After all the driving and 32oz of RedBull later (divided into one 20oz can and one 12oz can), Alex made it back to Canton safely and learnt that in order to do well in statistics, you actually need to understand what a sampling distribution is. He also learnt that he probably shouldn’t travel through the dacks when there is a travel ban (Don’t worry he had an unopened Army MRE on him, as well as an army sleeping bag and 1L of water in his Nalgene).
